version: "2.1"

services:
    icmp-server:
        image: icmp-server
        build: .
        environment:
            NODE_ENV: production
        ports:
            - 3000:3000
        volumes:
            - "./database:/database"
            - "./public:/public"
